### ISSUE TITLE
Change mypy from release to developement depmendency

### ISSUE THREAD

**Issue by josteinl** [gb-libs/pydantic-geojson#25]
I see that mypy is listed as a dependency in the 
`pyproject.toml` 

```toml
[tool.poetry.dependencies]
mypy = "^1.4.1"  # <-- Suggest moving to dev.dependencies

[tool.poetry.group.dev.dependencies]
mypy = "*"  # <-- Suggest moving mypy here
```

Also, suggest moving everything from the section `[tool.poetry.dev-dependencies]` to `[tool.poetry.group.dev.dependencies]`.

If you want a PR, please let me know.

I have not checked if you actually use mypy in your code.
